FROM fedora:25

RUN dnf makecache && dnf install -y \
    python-pip \
    python-virtualenv \
    git-core \
    gcc \
    redhat-rpm-config \
    which \
    findutils \
    procps-ng \
    sudo \
    perl \
    debootstrap \
    qemu-img \
    parted \
    cpio \
    gnupg \
    kpartx
RUN git clone https://github.com/openstack-infra/nodepool.git --branch feature/zuulv3
RUN virtualenv /srv/nodepool
RUN /srv/nodepool/bin/pip install ./nodepool
RUN pip install diskimage-builder
RUN mkdir -p \
    /etc/nodepool/ \
    /opt/nodepool/images

RUN useradd -u 1000 -d /var/lib/nodepool nodepool
RUN chown -R nodepool:nodepool \
    /opt/nodepool/images \
    /etc/nodepool/
RUN echo "nodepool ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/99_nodepool_suoders
RUN chmod 0400 /etc/sudoers.d/99_nodepool_suoders

USER nodepool
RUN mkdir -p \
    /var/lib/nodepool/.config/openstack
RUN ln -s /run/secrets/clouds.yaml ~/.config/openstack/clouds.yaml

COPY root/etc/nodepool /etc/nodepool

CMD /bin/bash
