version: '3.1'
services:
  zuul-scheduler:
    restart: always
    container_name: zuul-scheduler
    build:
      context: .
      dockerfile: Dockerfile-zuul-fedora
    command: /srv/zuul/bin/zuul-scheduler -d -c /run/secrets/zuul.conf
    ports:
      - 8001:8001
    links:
      - zuul-zookeeper
    secrets:
      - zuul.conf
  zuul-executor:
    restart: always
    container_name: zuul-executor
    build:
      context: .
      dockerfile: Dockerfile-zuul-fedora
    command: /srv/zuul/bin/zuul-executor -d -c /run/secrets/zuul.conf
    links:
      - zuul-zookeeper
    secrets:
      - zuul.conf
  zuul-zookeeper:
    restart: always
    container_name: zuul-zookeeper
    image: zookeeper:latest
  nodepool-launcher:
    #restart: always
    container_name: nodepool-launcher
    build:
      context: .
      dockerfile: Dockerfile-nodepool-fedora
    command: /srv/nodepool/bin/nodepool-launcher -d
    links:
      - zuul-zookeeper
  nodepool-builder:
    #restart: always
    container_name: nodepool-builder
    build:
      context: .
      dockerfile: Dockerfile-nodepool-fedora
    command: /srv/nodepool/bin/nodepool-builder -d
    links:
      - zuul-zookeeper
secrets:
  zuul.conf:
    file: ./zuul.conf.secret
