version: '3.1'
services:
  zuul-scheduler:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-zuul-fedora
    command: /srv/zuul/bin/zuul-scheduler -d -c /run/secrets/zuul.conf
    ports:
      - 8001:8001
    secrets:
      - source: zuul.conf
        target: zuul.conf
        uid: '1000'
        gid: '1000'
  zuul-executor:
    user: root
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-zuul-fedora
    command: /srv/zuul/bin/zuul-executor -d -c /run/secrets/zuul.conf
    secrets:
      - source: zuul.conf
        target: zuul.conf
        uid: '1000'
        gid: '1000'
      - zuul.conf
  zuul-zookeeper:
    restart: always
    image: zookeeper:latest
  nodepool-launcher:
    #restart: always
    build:
      context: .
      dockerfile: Dockerfile-nodepool-fedora
    command: /srv/nodepool/bin/nodepool-launcher -d
    secrets:
      - source: clouds.yaml
        target: clouds.yaml
        uid: '1000'
        gid: '1000'
  nodepool-builder:
    #restart: always
    build:
      context: .
      dockerfile: Dockerfile-nodepool-fedora
    command: /srv/nodepool/bin/nodepool-builder -d
    privileged: true
    secrets:
      - source: clouds.yaml
        target: clouds.yaml
        uid: '1000'
        gid: '1000'
    volumes:
      - /opt/nodepool/images
      - /tmp/
secrets:
  zuul.conf:
    file: ./zuul.conf.secret
  clouds.yaml:
    file: ./clouds.yaml.secret
