version: '3.1'
services:
  zuul-scheduler:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-zuul-fedora
    command: /srv/zuul/bin/zuul-scheduler -d -c /run/secrets/zuul.conf
    ports:
      - 8001:8001
    secrets:
      - zuul.conf
  zuul-executor:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-zuul-fedora
    command: /srv/zuul/bin/zuul-executor -d -c /run/secrets/zuul.conf
    secrets:
      - zuul.conf
  zuul-zookeeper:
    restart: always
    image: zookeeper:latest
  nodepool-launcher:
    #restart: always
    build:
      context: .
      dockerfile: Dockerfile-nodepool-fedora
    command: /srv/nodepool/bin/nodepool-launcher -d
  nodepool-builder:
    #restart: always
    build:
      context: .
      dockerfile: Dockerfile-nodepool-fedora
    command: /srv/nodepool/bin/nodepool-builder -d
secrets:
  zuul.conf:
    file: ./zuul.conf.secret
